-- MySQL Script generated by MySQL Workbench
-- 10/12/17 03:41:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema siderval
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema siderval
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `siderval` DEFAULT CHARACTER SET utf8 ;
USE `siderval` ;

-- -----------------------------------------------------
-- Table `siderval`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siderval`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `creacion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `tipo` INT NOT NULL DEFAULT 2,
      PRIMARY KEY (`iduser`));


-- -----------------------------------------------------
-- Table `siderval`.`material`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siderval`.`material` (
  `idmaterial` INT NOT NULL AUTO_INCREMENT,
  `u_medida` VARCHAR(10) NULL,
  `f_aprov` VARCHAR(20) NULL,
  `leadtime` INT NULL,
  `precio` INT NULL,
  `abc` VARCHAR(1) NULL,
  `tipo` INT NOT NULL,
  `especificacion` INT NULL,
  `caracteristica` INT NULL,
  `idproducto` INT NULL,
  PRIMARY KEY (`idmaterial`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siderval`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siderval`.`Producto` (
  `idmaterial` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `aleacion` VARCHAR(45) NULL,
  `subaleacion` VARCHAR(45) NULL,
  `pdf` VARCHAR(200) NULL,
  INDEX `fk_Pterminado_material_idx` (`idmaterial` ASC),
  PRIMARY KEY (`idproducto`, `idmaterial`),
  CONSTRAINT `fk_Pterminado_material`
    FOREIGN KEY (`idmaterial`)
    REFERENCES `siderval`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siderval`.`Recurso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siderval`.`Recurso` (
  `idmaterial` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `u_pedido` VARCHAR(10) NULL,
  `cod_proveedor` INT NULL,
  `punto_pedido` VARCHAR(50) NULL,
  PRIMARY KEY (`idmaterial`, `idproducto`),
  CONSTRAINT `fk_Recurso_material1`
    FOREIGN KEY (`idmaterial`)
    REFERENCES `siderval`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siderval`.`Otro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siderval`.`Otro` (
  `idmaterial` INT NOT NULL,
  `idproducto` INT NOT NULL,
  `helper` VARCHAR(45) NULL,
  PRIMARY KEY (`idmaterial`, `idproducto`),
  CONSTRAINT `fk_Otro_material1`
    FOREIGN KEY (`idmaterial`)
    REFERENCES `siderval`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `siderval`.`Bom`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `siderval`.`Bom` (
  `idproducto` INT NOT NULL,
  `idmaterial_master` INT NOT NULL,
  `idmaterial_slave` INT NOT NULL,
  `cantidad` INT NULL,
  PRIMARY KEY (`idproducto`, `idmaterial_master`, `idmaterial_slave`),
  INDEX `fk_Producto_has_material_material1_idx` (`idmaterial_slave` ASC),
  INDEX `fk_Producto_has_material_Producto1_idx` (`idproducto` ASC, `idmaterial_master` ASC),
  CONSTRAINT `fk_Producto_has_material_Producto1`
    FOREIGN KEY (`idproducto` , `idmaterial_master`)
    REFERENCES `siderval`.`Producto` (`idproducto` , `idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Producto_has_material_material1`
    FOREIGN KEY (`idmaterial_slave`)
    REFERENCES `siderval`.`material` (`idmaterial`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE USER 'user' IDENTIFIED BY '1234';

GRANT SELECT ON TABLE `siderval`.* TO 'user';
CREATE USER 'admin' IDENTIFIED BY '1234';

GRANT ALL ON `siderval`.* TO 'admin';
GRANT SELECT ON TABLE `siderval`.* TO 'admin';
GRANT SELECT, INSERT, TRIGGER ON TABLE `siderval`.* TO 'admin';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `siderval`.* TO 'admin';
GRANT EXECUTE ON ROUTINE `siderval`.* TO 'admin';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
